/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * lolappAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * 
 * @export
 * @interface Summoner
 */
export interface Summoner {
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Summoner
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Summoner
     */
    updatedOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    summonerID?: string;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    accountID?: string;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    puuid?: string;
    /**
     * 
     * @type {string}
     * @memberof Summoner
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof Summoner
     */
    profileIconID?: number;
    /**
     * 
     * @type {Date}
     * @memberof Summoner
     */
    revisionDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof Summoner
     */
    summonerLevel?: number;
}
/**
 * SummonerApi - fetch parameter creator
 * @export
 */
export const SummonerApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [username] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summonerGetSummonerGet(username?: string, options: any = {}): FetchArgs {
            const localVarPath = `/Summoner/getSummoner`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SummonerApi - functional programming interface
 * @export
 */
export const SummonerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} [username] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summonerGetSummonerGet(username?: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Summoner> {
            const localVarFetchArgs = SummonerApiFetchParamCreator(configuration).summonerGetSummonerGet(username, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * SummonerApi - factory interface
 * @export
 */
export const SummonerApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * 
         * @param {string} [username] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        summonerGetSummonerGet(username?: string, options?: any) {
            return SummonerApiFp(configuration).summonerGetSummonerGet(username, options)(fetch, basePath);
        },
    };
};

/**
 * SummonerApi - object-oriented interface
 * @export
 * @class SummonerApi
 * @extends {BaseAPI}
 */
export class SummonerApi extends BaseAPI {
    /**
     * 
     * @param {string} [username] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SummonerApi
     */
    public summonerGetSummonerGet(username?: string, options?: any) {
        return SummonerApiFp(this.configuration).summonerGetSummonerGet(username, options)(this.fetch, this.basePath);
    }

}
